# config/_default/menus.toml

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Topics"
pageRef = "topics"
weight = 20

[[main]]
pre = "github"
name = "GitHub"
url = "https://github.com/nggih"
weight = 30

[[footer]]
name = "Privacy"
url = "https://external-link"
